[workspace]
resolver = "3"
members = ["network", "network-common", "network-libp2p", "network-types"]

[workspace.dependencies]
thiserror = "2.0.17"
serde = { version = "1.0.228" }

[profile.release]
codegen-units = 1
